### ISSUE TITLE
field level access for sugarcrm 6.5

### ISSUE THREAD

**Issue by noamtahan** [ernierasta/Field-Level-Access-Control-for-SugarCRM#1]
Hi,
This version of the "field level access" module work also on sugarcrm version 6.5?
Thanks

**Comment by ernierasta** [comment]
Hi! Sorry for late answer. Well, i stopped developing for SugarCRM long time ago, so I am not sure If I manage it to work, but from what I remember generally it works. For sure it will need some fiddling, but give it a try. It will be great if you let us know if it is worth anything.

Sorry I can not help You more.
